apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collect-metrics
  namespace: kube-state-metrics
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]