global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  receiver: 'telegram'
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: 'токен бота' 
    chat_id: 1234    # удалил из соображений безопасности, но можете подставить свои значения и все работает :)